#!/usr/bin/env bash
set -e
if [[ -d .git ]]; then
  REV=`git describe --always`
  npm run build
  rm -rf _public
  git clone $(git remote get-url origin) --depth 1 -b gh-pages _public
  cd _public
  git rm -r *
  cp -R ../static/summit2024/* ./
  git add *
  git commit -m "regen for $REV"
  git push
  cd ..
  rm -rf _public
else
  echo "please use deploy under a git repo."
fi
