#!/usr/bin/env bash
set -e
if [[ -d .git ]]; then
  REV=`git describe --always`
  rm -rf _public
  git clone $(git remote get-url origin) --depth 1 -b release _public
  cd _public
  git rm -r *
  cp -R ../web/static ./static
  #cp -R ../web/view ./view
  cp -R ../dist ./
  git add *
  git commit -m "regen for $REV"
  git push
  cd ..
  rm -rf _public
else
  echo "please use deploy under a git repo."
fi
